version: '3.8'

services:
  redis:
    image: redis:7.4
    container_name: redis
    restart: always
    ports:
      - ${REDIS_BINDING_PORT}:${REDIS_PORT} # You should set your ports in .env 
    volumes:
      - redis-data:/data # This stores all data inside Redis (for data persistence!)

  connect:
    build: .
    container_name: python-connect
    restart: always
    depends_on:
      - redis
    volumes:
      - .:/redis-latency-test
    env_file:
     - .env

volumes:
  redis-data:


